=== foresightyoue/exchange/ry-app/src/Database.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:include schemaLocation="RecordSet.xsd" />
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="caption" type="xs:string" />
                <xs:element name="home" type="xs:string" />
                <xs:element name="include" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="caption" />
                        </xs:sequence>
                        <xs:attribute name="filename" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="tables">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="table" type="table" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="script" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="procedure" type="scriptfile" minOccurs="0" maxOccurs="unbounded" />
                            <xs:element name="function" type="scriptfile" minOccurs="0" maxOccurs="unbounded" />
                            <xs:element name="trigger" type="scriptfile" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="table">
        <xs:sequence>
            <xs:element name="name" type="caption" />
            <xs:element name="remark" type="xs:string" />
            <xs:element name="menus" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="item" type="MenuItem" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="fields">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="field" type="field" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="indexs" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="index" type="index" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="records" type="Records" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="code" type="xs:string" use="required" />
        <xs:attribute name="custom" type="xs:boolean" />
        <xs:attribute name="delete" type="xs:boolean" use="optional" default="false" />
        <xs:attribute name="qcdate" type="xs:date" use="optional" />
        <xs:attribute name="author" type="xs:string" use="optional" />
        <xs:attribute name="database" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="" />
                    <xs:enumeration value="Common" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="removever" type="xs:boolean" use="optional" />
        <xs:attribute name="movehistory" type="xs:boolean" use="optional" />
        <!-- 是否移除历史版本记录，若为true则须建立历史版本数据表 -->
        <!-- 是否移动历史数据记录，若为true则须建立历史数据库 -->
    </xs:complexType>
    <xs:complexType name="MenuItem">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="code" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="field">
        <xs:sequence>
            <xs:element name="name" type="caption" />
            <xs:element name="command" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="option" type="ValueOption" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="remark" type="xs:string" minOccurs="0" />
            <xs:element name="level" type="FieldLevel" minOccurs="0" />
            <xs:element name="select" type="FieldSelect" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="code" type="xs:string" use="required" />
        <xs:attribute name="type" type="FieldType" use="required" />
        <xs:attribute name="null" type="xs:boolean" use="required" />
        <xs:attribute name="default" type="xs:string" use="optional" />
        <xs:attribute name="readonly" type="xs:boolean" use="optional" />
        <xs:attribute name="width" type="xs:integer" use="optional" />
        <xs:attribute name="author" type="xs:string" use="optional" />
        <xs:attribute name="delete" type="xs:boolean" use="optional" default="false" />
        <xs:attribute name="qcdate" type="xs:date" use="optional" />
        <xs:attribute name="group" type="FieldGroup" />
    </xs:complexType>
    <xs:complexType name="FieldSelect">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="SelectType" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="SelectType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="buffer" />
            <xs:enumeration value="object" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="FieldLevel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="关键栏位" />
            <xs:enumeration value="备注栏位" />
            <xs:enumeration value="保留栏位" />
            <xs:enumeration value="未知栏位" />
            <xs:enumeration value="过期栏位" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="FieldGroup">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PartCode" />
            <xs:enumeration value="CusCode" />
            <xs:enumeration value="SupCode" />
            <xs:enumeration value="DeptCode" />
            <xs:enumeration value="CWCode" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ValueOption">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="value" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="FieldType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="char(2)" />
            <xs:enumeration value="char(6)" />
            <xs:enumeration value="varchar(1)" />
            <xs:enumeration value="varchar(2)" />
            <xs:enumeration value="varchar(3)" />
            <xs:enumeration value="varchar(4)" />
            <xs:enumeration value="varchar(5)" /> <!-- 存储时间专用 -->
            <xs:enumeration value="varchar(6)" />
            <xs:enumeration value="varchar(10)" />
            <xs:enumeration value="varchar(11)" />
            <xs:enumeration value="varchar(14)" />
            <xs:enumeration value="varchar(18)" /><!-- 料号编号 -->
            <xs:enumeration value="varchar(20)" />
            <xs:enumeration value="varchar(24)" />
            <xs:enumeration value="varchar(28)" />
            <xs:enumeration value="varchar(30)" />
            <xs:enumeration value="varchar(32)" />
            <xs:enumeration value="varchar(38)" /> <!-- guid专用 -->
            <xs:enumeration value="varchar(50)" />
            <xs:enumeration value="varchar(60)" />
            <xs:enumeration value="varchar(64)" />
            <xs:enumeration value="varchar(80)" />
            <xs:enumeration value="varchar(100)" />
            <xs:enumeration value="varchar(128)" />
            <xs:enumeration value="varchar(180)" />
            <xs:enumeration value="varchar(200)" />
            <xs:enumeration value="varchar(255)" />
            <xs:enumeration value="varchar(256)" />
            <xs:enumeration value="varchar(300)" />
            <xs:enumeration value="varchar(400)" />
            <xs:enumeration value="varchar(500)" />
            <xs:enumeration value="varchar(1000)" />
            <xs:enumeration value="varchar(1024)" />
            <xs:enumeration value="varchar(2000)" />
            <xs:enumeration value="varchar(2048)" />
            <xs:enumeration value="bit(1)" />
            <xs:enumeration value="date(10)" />
            <xs:enumeration value="datetime(19)" />
            <xs:enumeration value="timestamp(19)" />
            <xs:enumeration value="uniqueidentifier" />
            <xs:enumeration value="bigint(19)" />
            <xs:enumeration value="ubigint(19)" />
            <xs:enumeration value="int(11)" />
            <xs:enumeration value="tinyint(1)" />
            <xs:enumeration value="tinyint(4)" />
            <!-- <xs:enumeration value="tinyint" /> -->
            <!-- <xs:enumeration value="smallint" /> -->
            <xs:enumeration value="money" />
            <xs:enumeration value="decimal(11,2)" />
            <xs:enumeration value="decimal(16,6)" />
            <xs:enumeration value="decimal(18,4)" />
            <xs:enumeration value="decimal(18,6)" />
            <xs:enumeration value="decimal(20,8)" />
            <xs:enumeration value="decimal(28,8)" />
            <xs:enumeration value="float" />
            <xs:enumeration value="decimal" />
            <xs:enumeration value="text(65535)" />
            <xs:enumeration value="image" />
            <xs:enumeration value="blob(65535)" />
            <xs:enumeration value="mediumtext(16777215)" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="scriptfile">
        <xs:sequence>
            <xs:element name="param" type="ScriptParam" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="name" type="caption" />
            <xs:element name="remark" type="xs:string" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="code" type="xs:string" use="required" />
        <xs:attribute name="filename" type="xs:string" use="required" />
        <xs:attribute name="delete" type="xs:boolean" use="optional" default="false" />
        <xs:attribute name="author" type="xs:string" use="optional" />
        <xs:attribute name="qcdate" type="xs:date" use="optional" />
    </xs:complexType>
    <xs:complexType name="ScriptParam">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="remark" type="xs:string" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="code" type="xs:string" use="required" />
        <xs:attribute name="type" type="FieldType" use="required" />
        <xs:attribute name="data" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="in" />
                    <xs:enumeration value="out" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="default" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="index">
        <xs:sequence>
            <xs:element name="field" type="IndexField" maxOccurs="unbounded" />
            <xs:element name="include" type="IndexInclude" minOccurs="0" />
            <xs:element name="error" type="caption" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="code" type="xs:string" use="required" />
        <xs:attribute name="type" type="IndexType" use="required" />
        <xs:attribute name="clustered" type="xs:boolean" use="optional" />
        <xs:attribute name="delete" type="xs:boolean" use="optional" default="false" />
        <xs:attribute name="qcdate" type="xs:date" use="optional" />
    </xs:complexType>
    <xs:simpleType name="IndexType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="primary" />
            <xs:enumeration value="unique" />
            <xs:enumeration value="normal" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="IndexField">
        <xs:attribute name="code" type="xs:string" use="required" />
        <xs:attribute name="sort" type="sort" use="required" />
    </xs:complexType>
    <xs:simpleType name="sort">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ASC" />
            <xs:enumeration value="DESC" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="IndexInclude">
        <xs:sequence>
            <xs:element name="field" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="code" type="xs:string" use="required" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="caption">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="Records">
        <xs:sequence>
            <xs:element name="record" type="Record" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="mincount" type="xs:integer" use="required" />
        <xs:attribute name="maxcount" type="xs:integer" use="required" />
    </xs:complexType>
</xs:schema>

=== foresightyoue/exchange/ry-app/src/database.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="database.xsl"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="database.xsd">
    <caption>虚拟币交易所数据库结构</caption>
    <home></home>
    <tables>
        <table code="emailvalidate">
            <name>服务调用记录表</name>
            <remark />
            <fields>
                <field code="UID_" type="int(11)" null="false">
                    <name>主键UID</name>
                </field>
                <field code="CorpNo_" type="varchar(10)" null="false">
                    <name></name>
                </field>
                <field code="Service_" type="varchar(80)" null="false">
                    <name>执行服务</name>
                </field>
                <field code="Trans_" type="bit(1)" null="false">
                    <name>Trans_</name>
                </field>
                <field code="TickCount_" type="decimal(18,6)" null="false">
                    <name>执行毫秒时间</name>
                </field>
                <field code="AppUser_" type="varchar(10)" null="false">
                    <name>建档人员</name>
                </field>
                <field code="AppDate_" type="datetime(19)" null="true">
                    <name>建档日期</name>
                </field>
                <field code="Client_" type="bit(1)" null="false">
                    <name>是否客户端调用</name>
                </field>
                <field code="DataIn_" type="mediumtext(16777215)" null="true">
                    <name>传入参数</name>
                </field>
            </fields>
        </table>
        <table code="emailvalidate">
            <name>邮箱验证链接</name>
            <remark />
            <fields>
                <field code="fId" type="int(11)" null="false">
                    <name>主键Id</name>
                </field>
                <field code="fUuid" type="varchar(128)" null="false">
                    <name>发送邮件编号</name>
                </field>
                <field code="FUs_fId" type="int(11)" null="true">
                    <name>fuser.fId</name>
                </field>
                <field code="fCreateTime" type="datetime(19)" null="true">
                    <name>创建时间</name>
                </field>
                <field code="fValidateTime" type="datetime(19)" null="true">
                    <name>验证时间</name>
                </field>
                <field code="version" type="int(11)" null="true">
                    <name>版本</name>
                </field>
                <field code="type" type="int(11)" null="true">
                    <name>邮件类别</name>
                </field>
                <field code="fmail" type="varchar(128)" null="true">
                    <name>邮件地址</name>
                </field>
                <field code="fNewUUid" type="varchar(128)" null="true">
                    <name>新的发送邮件编号</name>
                </field>
            </fields>
        </table>
        <table code="fabout">
            <name>关于系统</name>
            <remark />
            <fields>
                <field code="fid" type="int(11)" null="false">
                    <name>主键fId</name>
                </field>
                <field code="ftitle" type="varchar(128)" null="true">
                    <name>标题-中文</name>
                </field>
                <field code="ftitle_en" type="varchar(128)" null="true">
                    <name>标题-英文</name>
                </field>
                <field code="ftitle_in" type="varchar(128)" null="true">
                    <name>标题-印度文</name>
                </field>
                <field code="fcontent" type="mediumtext(16777215)" null="true">
                    <name>内容-中文</name>
                </field>
                <field code="fcontent_en" type="mediumtext(16777215)" null="true">
                    <name>内容-英文</name>
                </field>
                <field code="fcontent_in" type="mediumtext(16777215)" null="true">
                    <name>内容-印度文</name>
                </field>
                <field code="ftype" type="varchar(100)" null="true">
                    <name>帮助类型-中文</name>
                </field>
                <field code="ftype_en" type="varchar(100)" null="true">
                    <name>帮助类型-英文</name>
                </field>
                <field code="ftype_in" type="varchar(100)" null="true">
                    <name>帮助类型-印度文</name>
                </field>
                <field code="fisview" type="tinyint(4)" null="true">
                    <name>是否可见</name>
                </field>
            </fields>
        </table>
        <table code="fadmin">
            <name>管理员列表</name>
            <remark />
            <fields>
                <field code="fId" type="int(11)" null="false">
                    <name>主键fId</name>
                </field>
                <field code="fName" type="varchar(32)" null="true">
                    <name>登录名</name>
                </field>
                <field code="fPassword" type="varchar(32)" null="true">
                    <name>密码</name>
                </field>
                <field code="fCreateTime" type="datetime(19)" null="true">
                    <name>创建时间</name>
                </field>
                <field code="fLevel" type="int(11)" null="true">
                    <name>等级</name>
                </field>
                <field code="fStatus" type="int(11)" null="true">
                    <name>状态</name>
                </field>
                <field code="version" type="int(11)" null="true">
                    <name>版本</name>
                </field>
                <field code="froleId" type="int(11)" null="true">
                    <name>frole.fid</name>
                </field>
                <field code="salt" type="varchar(50)" null="true">
                    <name>salt</name>
                </field>
                <field code="fuserid" type="int(11)" null="true">
                    <name>fuserid</name>
                </field>
                <field code="fregPass" type="varchar(50)" null="true">
                    <name>fregPass</name>
                </field>
                <field code="fwidPass" type="varchar(50)" null="true">
                    <name>fwidPass</name>
                </field>
            </fields>
        </table>
        <table code="fads">
            <name>广告列表</name>
            <remark />
            <fields>
                <field code="fid" type="int(11)" null="false">
                    <name></name>
                </field>
                <field code="ftitle" type="varchar(100)" null="true">
                    <name>中文标题</name>
                </field>
                <field code="ftitle_en" type="varchar(100)" null="true">
                    <name>英文标题</name>
                </field>
                <field code="fimages" type="varchar(100)" null="true">
                    <name>图片地址</name>
                </field>
                <field code="fcreatetime" type="datetime(19)" null="true">
                    <name>创建时间</name>
                </field>
                <field code="furl" type="varchar(100)" null="true">
                    <name>跳转链接</name>
                </field>
            </fields>
        </table>
        <table code="fapi">
            <name>第三方服务连接参数表</name>
            <remark />
            <fields>
                <field code="fid" type="int(11)" null="false">
                    <name></name>
                </field>
                <field code="fpartner" type="varchar(128)" null="true">
                    <name>合作伙伴</name>
                </field>
                <field code="fsecret" type="varchar(256)" null="true">
                    <name>链接</name>
                </field>
                <field code="fuser" type="int(11)" null="true">
                    <name>fuser.fId</name>
                </field>
                <field code="label" type="varchar(128)" null="true">
                    <name>相关信息</name>
                </field>
            </fields>
        </table>
        <table code="fappversion">
            <name>App版本信息表</name>
            <remark />
            <fields>
                <field code="fid" type="int(11)" null="false">
                    <name></name>
                </field>
                <field code="type" type="int(11)" null="false">
                    <name>app类别（0安卓 1苹果）</name>
                </field>
                <field code="update_readme" type="varchar(255)" null="true">
                    <name>版本更新日志</name>
                </field>
                <field code="version" type="varchar(32)" null="false">
                    <name>版本号</name>
                </field>
                <field code="update_reset" type="tinyint(1)" null="true">
                    <name>是否强制更新</name>
                </field>
                <field code="url" type="varchar(255)" null="true">
                    <name>app地址</name>
                </field>
                <field code="create_time" type="datetime(19)" null="true">
                    <name>创建时间</name>
                </field>
                <field code="update_time" type="datetime(19)" null="true">
                    <name>修改时间</name>
                </field>
            </fields>
        </table>
        <table code="farticle">
            <name>资讯列表</name>
            <remark />
            <fields>
                <field code="fId" type="int(11)" null="false">
                    <name>id</name>
                </field>
                <field code="fCreateAdmin" type="int(11)" null="true">
                    <name>fadmin.fId</name>
                </field>
                <field code="fModifyAdmin" type="int(11)" null="true">
                    <name>fadmin.fId</name>
                </field>
                <field code="fArticleType" type="int(11)" null="true">
                    <name>farticletype.fId</name>
                </field>
